#!/usr/bin/env bash

print_status_line () {
  local emojis
  if [ "$exitcode" -eq 0 ]; then
    emojis=('😀\[ \]' '😂\[ \]' '😉\[ \]' '😍\[ \]')
  else
    emojis=('😡\[  \]' '🤔\[ \]' '😢\[ \]')
  fi
  local len=${#emojis[@]}
  local idx=$(shuf -i "1-$len" -n 1)
  idx=$((idx-1))
  printf "%s" " ${emojis[$idx]}"
  if [ "$exitcode" -eq 0 ]; then
    printf '\[%s\] :)' "$(tput setaf 2)"
  else
    printf '\[%s\]-%s :(' "$(tput setaf 1)" "$exitcode"
  fi
}
