#!/usr/bin/env bash
export BASHRC="$HOME/.bashrc"
export VIMRC="$HOME/.vimrc"
export PROFILE="$HOME/.profile"
export I3CONFIG="$HOME/.config/i3/config"
export TMUXCONFIG="$HOME/.tmux.conf"
export HOLCONFIGDIR="$HOME/.holchain"
export GDBCONFIG="$HOME/.gdbinit"
alias uniqorder="awk '++m[\$0]==1'"
