#!/usr/bin/env bash
set -u
if [ $(uname) = 'Darwin' ]; then
  # TODO: test in linux
  DIR=$(dirname $(realpath "$0"))
else
  DIR=$(dirname "$(readlink -f "$0")")
fi
FROMTO="$(dirname "$DIR")/bin/fromto"
# shellcheck source=/dev/null
source "$DIR/common"
sudo -k

include_in() {
  DST_FILE="$1"
  LINE_TO_ADD="$2"
  COMMENT_CHAR="$3"
  FULL_LINE="$LINE_TO_ADD $COMMENT_CHAR  Added by holchain"
  if grep --quiet "$FULL_LINE" "$DST_FILE"; then
    echo "  Already exists in $(basename "$DST_FILE")"
  else
    echo "$FULL_LINE" >> "$DST_FILE"
    echo "  Appended config to $(basename "$DST_FILE")"
  fi
}

add_to() {
  DST_FILE="$1"
  FILE_TO_ADD="$2"
  COMMENT_CHAR="$3"
  BEGIN_LINE="$COMMENT_CHAR  Begin holchain block"
  END_LINE="$COMMENT_CHAR  End holchain block"
  if [ ! -e "$DST_FILE" ]; then
    echo "  $DST_FILE does not exist, skipping"
    return
  fi
  grep --quiet "$BEGIN_LINE" "$DST_FILE"
  LINES_NOT_FOUND=$?
  TMPFILE=$(mktemp)
  # shellcheck source=/dev/null
  {
    . "$FROMTO" -vft "$BEGIN_LINE" "$END_LINE" < "$DST_FILE"
    echo "$BEGIN_LINE"
    cat "$FILE_TO_ADD"
    echo "$END_LINE"
  } >> "$TMPFILE"
  cp "$DST_FILE" "$FILE_TO_ADD.backup" || exit 1
  mv "$TMPFILE" "$DST_FILE"
  if [ $LINES_NOT_FOUND -eq 0 ]; then
    echo "  Updated config in $DST_FILE"
  else
    echo "  Added config to $DST_FILE"
  fi
}

write_to() {
  DST_FILE="$1"
  LINE="$2"
  ACTING_USER="$3"
  if [ -f "$DST_FILE" ]; then
    if [ "$LINE" = "$(cat "$DST_FILE")" ]; then
      echo "  $DST_FILE is up to date"
      return
    fi
  fi
  echo "$LINE" | sudo -u "$ACTING_USER" tee "$DST_FILE" > /dev/null
  echo "  Updated $DST_FILE"
}

vim_plugin() {
  GIT_URL="$1"
  BUNDLE_PATH="$HOME/.vim/bundle"
  mkdir -p "$BUNDLE_PATH"
  PACKAGE_NAME=$(echo "$GIT_URL" | sed -E 's:^.*/(.+)\.git:\1:')
  TARGET_PATH="$BUNDLE_PATH/$PACKAGE_NAME"
  if [ -d "$TARGET_PATH" ]; then
    echo "  vim plugin $PACKAGE_NAME already exists"
  elif [ ! -e "$TARGET_PATH" ]; then
    echo "  getting vim plugin $PACKAGE_NAME"
    git clone "$GIT_URL" "$TARGET_PATH"
  else
    echo "  vim plugin $PACKAGE_NAME cannot be downloaded"
  fi
}

echo 'adding rc files'
include_in "$BASHRC" "source $DIR/bashrc" "#"
include_in "$PROFILE" "source $DIR/profile" "#"
include_in "$VIMRC" "source $DIR/vimrc" '"'
add_to "$I3CONFIG" "$DIR/i3config" "#"
add_to "$TMUXCONFIG" "$DIR/tmuxconf" "#"

if [ $(uname) != 'Darwin' ]; then
  echo 'updating system config'
  write_to '/etc/ld.so.conf.d/locallib.conf' '/usr/local/lib' 'root'
fi

echo 'creating directories'
mkdir -p "$HOME/screenshots"
mkdir -p "$HOLCONFIGDIR"

echo 'downloading vim plugins'
if [ ! -e ~/.vim/autoload ]; then
  mkdir -p ~/.vim/autoload
  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi
vim_plugin 'https://github.com/wikitopian/hardmode.git'
vim_plugin 'https://github.com/scrooloose/nerdtree.git'
vim_plugin 'https://github.com/theevocater/thrift.vim.git'
vim_plugin 'https://github.com/wincent/command-t.git'
